version: '3.3'

services:
  flag_reader:
    build: .
    container_name: cjayl
    ports:
      - '2038:2038'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 50M

    healthcheck:
      test: socat - TCP4:localhost:2038 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
