version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: nexus-mainframe
    ports:
      - '2021:22'
    healthcheck:
      test: socat - TCP4:localhost:22 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
